-- ================================================
-- WHATSAPP CLONE - COMPLETE DATABASE SETUP
-- Run this ONCE in Supabase SQL Editor
-- ================================================

-- 1. PROFILES TABLE
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  phone text unique,
  about text default 'Hey there! I am using ChatVerse.',
  avatar_url text,
  is_online boolean default false,
  last_seen timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
alter table profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone"
  on profiles for select using (true);

create policy "Users can insert their own profile"
  on profiles for insert with check (auth.uid() = id);

create policy "Users can update their own profile"
  on profiles for update using (auth.uid() = id);

-- ================================================
-- 2. MESSAGES TABLE
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  content text,
  sender_id uuid references profiles(id) on delete cascade not null,
  receiver_id uuid references profiles(id) on delete cascade not null,
  is_read boolean default false,
  media_url text
);

-- Enable RLS
alter table messages enable row level security;

-- Policies for messages
create policy "Users can view their own messages"
  on messages for select
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Users can send messages"
  on messages for insert
  with check (auth.uid() = sender_id);

create policy "Receiver can mark messages as read"
  on messages for update
  using (auth.uid() = receiver_id);

-- ================================================
-- 3. CONTACTS TABLE
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  contact_id uuid references profiles(id) on delete cascade not null,
  created_at timestamp with time zone default now(),
  unique(user_id, contact_id)
);

-- Enable RLS
alter table contacts enable row level security;

-- Policies for contacts
create policy "Users can view their own contacts"
  on contacts for select using (auth.uid() = user_id);

create policy "Users can add contacts"
  on contacts for insert with check (auth.uid() = user_id);

create policy "Users can delete their contacts"
  on contacts for delete using (auth.uid() = user_id);

-- ================================================
-- 4. STATUS/STORIES TABLE
create table if not exists status_stories (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  media_url text,
  caption text,
  created_at timestamp with time zone default now(),
  expires_at timestamp with time zone default (now() + interval '24 hours')
);

-- Enable RLS
alter table status_stories enable row level security;

-- Policies for status
create policy "Users can view active stories"
  on status_stories for select
  using (expires_at > now());

create policy "Users can post their own stories"
  on status_stories for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own stories"
  on status_stories for delete
  using (auth.uid() = user_id);

-- ================================================
-- 5. ENABLE REALTIME
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table profiles;
alter publication supabase_realtime add table contacts;
alter publication supabase_realtime add table status_stories;

-- ================================================
-- 6. MESSAGE DELETE POLICY
create policy "Users can delete their own messages"
  on messages for delete
  using (auth.uid() = sender_id);

-- ================================================
-- 7. STORAGE BUCKETS (Run this in Supabase SQL or create manually in Storage tab)
-- Create buckets for avatars and chat images
insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true) on conflict do nothing;
insert into storage.buckets (id, name, public) values ('chat-images', 'chat-images', true) on conflict do nothing;

-- Storage policies
create policy "Anyone can view avatars" on storage.objects for select using (bucket_id = 'avatars');
create policy "Users can upload avatars" on storage.objects for insert with check (bucket_id = 'avatars' and auth.role() = 'authenticated');
create policy "Anyone can view chat images" on storage.objects for select using (bucket_id = 'chat-images');
create policy "Users can upload chat images" on storage.objects for insert with check (bucket_id = 'chat-images' and auth.role() = 'authenticated');

-- ================================================
-- DONE! Your database is ready.
-- ================================================
